### ISSUE TITLE
 Unhandled Promise rejection: (SystemJS) XHR error

### ISSUE THREAD

**Issue by karthikkavin** [phenomnomnominal/angular-2-local-storage#11]
zone.js:484 Unhandled Promise rejection: (SystemJS) XHR error (404 Not Found) loading http://localhost:4200/vendor/angular-2-local-storage/index.js
When ng build is done the dist/vendor/angular-2-local-storage indside not have index.js file.
I am used your document. my system-config.ts file is
const map: any = { 
  'angular-2-local-storage': 'vendor/angular-2-local-storage',
};
const packages: any = {
  'angular-2-local-storage': { main: 'index.js', defaultExtension: 'js' },
}
const barrels: string[] = [
// Thirdparty barrels.
  'rxjs',
  'angular-2-local-storage',
]

Please help.

**Comment by JavoByte** [comment]
Same here, using `2.0.0-rc.6`

**Comment by karthikkavin** [comment]
i have to update angular 2.0 latest release. How use and config.
Please advise.

**Comment by elwynelwyn** [comment]
Closing - I suspect this is due to incorrect SystemJS config (there is no `index.js` in the package, it should point at `dist/angular-2-local-storage.js`.
Check #20 for some example SystemJS config, or, if you're using WebPack, it will just work without any config (due to the `main` entry in `package.json`)
